### ISSUE TITLE
java.lang.NoSuchMethodError: android.widget.FrameLayout.<init>

### ISSUE THREAD

**Issue by Martin-Hogge** [MiguelCatalan/MaterialSearchView#73]
The library is working with my Samsung S5 (LOLIPOP - 5.0) but when I try it on a Huawei G7-L01 (KITKAT - 4.4.4) I got this exception : 

> java.lang.NoSuchMethodError: android.widget.FrameLayout.<init>
>  at com.lapism.searchview.view.SearchView.<init>(SearchView.java:115)

Which is on the line : 

`super(context, attrs, defStyleAttr, defStyleRes);`

of the constructor.

Any idea how to fix this?

**Comment by AngeeelD** [comment]
I have the same problem, you know how to solve?
